#!/bin/bash

ENV_NAME="deepfold2-dev"
ENV_ALIGN_NAME="align"

CONDA_BASE=${CONDA_BASE:-"$HOME/conda"}
DEEPFOLD_BASE=${DEEPFOLD_BASE:-"$PWD"}
DATABASE_BASE=${DATABASE_BASE:-"/scratch/database/casp16"}

PYTHONPATH=$DEEPFOLD_BASE${PYTHONPATH:+:${PYTHONPATH}}
